from brownie import accounts, config
import os


def deploy_simple_storage():
    #account = accounts[0] #get account generated by brownie
    #account = accounts.load('whiterose') #get account added from the command line
    #account = accounts.add(os.getenv('PRIVATE_KEY')) #get account from environment variable
    account = account.add(config['wallets']['from_key']) #loading account from config file
    print(account)


def main():  # will be called when script is run
    deploy_simple_storage()
 